version: "3"
services:
  db:
    image: postgres
    container_name: postgres-migrate
    environment:
      - POSTGRES_PASSWORD=Password#123
      - POSTGRES_DB=customers
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway
    container_name: flyway-migrate
    command: migrate
    volumes:
      - ./sql:/flyway/sql
      - ./conf:/flyway/conf
    depends_on:
      - db
